### ISSUE TITLE
Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by navnitkapa** [ConnerAiken/mern-boilerplate#10]
ERROR in ./src/client/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/media/dev/mern-boilerplate/node_modules/babel-loader/lib/index.js:10:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js babel-polyfill react-hot-loader/patch ./src/client/index.js main[4]

**Comment by ConnerAiken** [comment]
Fixed /w https://github.com/ConnerAiken/mern-boilerplate/commit/c73a146cb8ae85e6879107125e6092f8e6b9d4ca
